package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Agreement extends RouteBuilder {

    public void configure() {

        rest()
           .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/agreement/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureAgreement")
                .description("Update details of the customer agreement")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Agreement Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureAgreement")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/agreement/{bqReferenceId}/exchange")
                .id("exchangeCustomerOfferProcedureAgreementUpdate")
                .description("Accept, verify, etc. actions against the customer and product agreements")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Agreement request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureAgreementUpdate")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/agreement/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureAgreement")
                .description("Retrieve details about the agreements impacted and created as part of the offer .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAgreementRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureAgreement");

        from("direct:updateCustomerOfferProcedureAgreement").to("log:updateCustomerOfferProcedureAgreement?level=INFO");
        from("direct:exchangeCustomerOfferProcedureAgreementUpdate")
                .to("log:exchangeCustomerOfferProcedureAgreementUpdate?level=INFO");
        from("direct:retrieveCustomerOfferProcedureAgreement")
                .to("log:retrieveCustomerOfferProcedureAgreement?level=INFO");
    }
}
