package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Audit extends RouteBuilder {

    public void configure() {

        rest()
           .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/audit/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureAudit")
                .description("Update details of submitted materials for audit checks")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Audit Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Audit Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureAudit")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/audit/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureAudit")
                .description("Retrieve details of the compliance assessment .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Audit Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAuditRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureAudit");

        from("direct:updateCustomerOfferProcedureAudit").to("log:updateCustomerOfferProcedureAudit?level=INFO");
        from("direct:retrieveCustomerOfferProcedureAudit").to("log:retrieveCustomerOfferProcedureAudit?level=INFO");
    }
}
