package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Booking extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/booking/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureBooking")
                .description("Update details of the offer asset and liability booking")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Booking Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Booking Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureBooking")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/booking/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureBooking")
                .description("Retrieve details about the booking .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Booking Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQBookingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureBooking");

        from("direct:updateCustomerOfferProcedureBooking").to("log:updateCustomerOfferProcedureBooking?level=INFO");
        from("direct:retrieveCustomerOfferProcedureBooking").to("log:retrieveCustomerOfferProcedureBooking?level=INFO");
    }
}
