package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Compliance extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/compliance/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureCompliance")
                .description("Update details submitted for compliance checks")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Compliance Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Compliance Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCompliance")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/compliance/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureCompliance")
                .description("Retrieve details of the regulatory compliance assessment .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Compliance Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQComplianceRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCompliance");

        from("direct:updateCustomerOfferProcedureCompliance")
                .to("log:updateCustomerOfferProcedureCompliance?level=INFO");
        from("direct:retrieveCustomerOfferProcedureCompliance")
                .to("log:retrieveCustomerOfferProcedureCompliance?level=INFO");
    }
}
