package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class CorrespondenceAndDocuments extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/correspondenceanddocuments/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureCorrespondenceandDocuments")
                .description("Update details about the correspondence and documents accessed and created by the offer")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CorrespondenceandDocuments Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCorrespondenceandDocuments")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/correspondenceanddocuments/{bqReferenceId}/exchange")
                .id("exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate")
                .description("Accept, verify, etc. correspondence and documents")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CorrespondenceandDocuments request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/correspondenceanddocuments/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureCorrespondenceandDocuments")
                .description("Retrieve details about correspondence and documents from the customer offer procedure .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQCorrespondenceandDocumentsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCorrespondenceandDocuments");
                
        from("direct:updateCustomerOfferProcedureCorrespondenceandDocuments")
                .to("log:updateCustomerOfferProcedureCorrespondenceandDocuments?level=INFO");
        from("direct:exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate")
                .to("log:exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate?level=INFO");
        from("direct:retrieveCustomerOfferProcedureCorrespondenceandDocuments")
                .to("log:retrieveCustomerOfferProcedureCorrespondenceandDocuments?level=INFO");
    }
}
