package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Disclosures extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/disclosures/{bqReferenceId}/update")
                .id("updateCustomerOfferProcedureDisclosures")
                .description("Update disclosure submission")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Disclosures Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureDisclosures")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/disclosures/{bqReferenceId}/exchange")
                .id("exchangeCustomerOfferProcedureDisclosuresUpdate")
                .description("Accept, reject etc. disclosures")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Disclosures request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureDisclosuresUpdate")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/disclosures/{bqReferenceId}/")
                .id("retrieveCustomerOfferProcedureDisclosures")
                .description("Retrieve details about disclosure submissions .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQDisclosuresRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureDisclosures");

        from("direct:updateCustomerOfferProcedureDisclosures")
                .to("log:updateCustomerOfferProcedureDisclosures?level=INFO");
        from("direct:exchangeCustomerOfferProcedureDisclosuresUpdate")
                .to("log:exchangeCustomerOfferProcedureDisclosuresUpdate?level=INFO");
        from("direct:retrieveCustomerOfferProcedureDisclosures")
                .to("log:retrieveCustomerOfferProcedureDisclosures?level=INFO");
    }
}
