package com.redhat.mercury.customeroffer.procedure;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class ProcedureBase extends RouteBuilder {

    public void configure() {

        rest()
            .post("/customer-offer/{sdReferenceId}/customer-offer-procedure/initiation")
                .id("initiateCustomerOfferProcedure")
                .description("Initiate the offer procedure")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CustomerOfferProcedure Request Payload")
                .endParam()
                .to("direct:initiateCustomerOfferProcedure")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/update")
                .id("updateCustomerOfferProcedure")
                .description("Update details of an offer procedure")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedure")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/control")
                .id("controlCustomerOfferProcedureUpdate")
                .description("Control the processing of an offer (e.g. terminate)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:controlCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/exchange")
                .id("exchangeCustomerOfferProcedureUpdate")
                .description("Accept, reject, verify, etc an offer procedure")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/execution")
                .id("executeCustomerOfferProcedureUpdate")
                .description("Execute an automated task against an offer (e.g. submit data)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:executeCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}/requisition")
                .id("requestCustomerOfferProcedureUpdate")
                .description("Request manual intervention in an offer (e.g. request specialist support)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:requestCustomerOfferProcedureUpdate")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure/{crReferenceId}")
                .id("retrieveCustomerOffer")
                .description("Retrieve details about a customer offer")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/CRCustomerOfferProcedureRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOffer")
            .get("/customer-offer/{sdReferenceId}/customer-offer-procedure")
                .id("RetrieveCustomerOfferReferenceIds")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- CustomerOffer Instance Status='active'")
                .endParam()
                .to("direct:RetrieveCustomerOfferReferenceIds");
    }
}
