package com.redhat.mercury.customecreditrating.state;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class Alerts extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/alerts/{bqReferenceId}/capture")
                .id("captureCustomerCreditRatingStateAlertsUpdate")
                .description("Capture notification of a credit alert")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Alerts Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Alerts request payload")
                .endParam()
                .to("direct:captureCustomerCreditRatingStateAlertsUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/alerts/{bqReferenceId}/")
                .id("retrieveCustomerCreditRatingStateAlerts")
                .description("Retrieve details about a credit alert .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Alerts Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAlertsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRatingStateAlerts");
    }
    
}
