package com.redhat.mercury.customecreditrating.state;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class ExternalReporting extends RouteBuilder {

    public void configure() {

        rest()
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/externalreporting/{bqReferenceId}/capture")
                .id("captureCustomerCreditRatingStateExternalReportingUpdate")
                .description("Capture external credit reports to support credit analysis and state")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ExternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ExternalReporting request payload")
                .endParam()
                .to("direct:captureCustomerCreditRatingStateExternalReportingUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/externalreporting/{bqReferenceId}/")
                .id("retrieveCustomerCreditRatingStateExternalReporting")
                .description("Retrieve details about external reporting to the credit monitoring activity .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ExternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQExternalReportingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRatingStateExternalReporting");
    }
    
}
