package com.redhat.mercury.customecreditrating.state;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

public final class State extends RouteBuilder {

    public void configure() {

        rest()
            .post("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/initiation")
                .id("initiateCustomerCreditRatingState")
                .description("Initiate credit state monitoring for a customer")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CustomerCreditRatingState Request Payload")
                .endParam()
                .to("direct:initiateCustomerCreditRatingState")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/control")
                .id("controlCustomerCreditRatingStateUpdate")
                .description("Control credit state monitoring (e.g. high frequency update)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:controlCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/exchange")
                .id("exchangeCustomerCreditRatingStateUpdate")
                .description("Accept, reject, etc credit state monitoring content")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:exchangeCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/execution")
                .id("executeCustomerCreditRatingStateUpdate")
                .description("Execute an automated task for credit state (e.g. auto refresh)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:executeCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/requisition")
                .id("requestCustomerCreditRatingStateUpdate")
                .description("Request manual intervention for credit state (e.g. revise underlying assessment)")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:requestCustomerCreditRatingStateUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}")
                .id("retrieveCustomerCreditRating")
                .description("Retrieve details about credit state monitoring for a customer")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/CRCustomerCreditRatingStateRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRating")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state")
                .id("RetrieveCustomerCreditRatingReferenceIds")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- CustomerCreditRating Instance Status='active'")
                .endParam()
                .to("direct:RetrieveCustomerCreditRatingReferenceIds")
            .get("/customer-credit-rating/customer-credit-rating-state/behavior-qualifiers/")
                .id("RetrieveCustomerCreditRatingBehaviorQualifiers")
                .produces("application/json")
                .to("direct:RetrieveCustomerCreditRatingBehaviorQualifiers")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/{behavior-qualifier}/")
                .id("RetrieveCustomerCreditRatingBehaviorQualifierReferenceIds")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("behavior-qualifier")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Behavior Qualifier Name. ex- ExternalReporting")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- ExternalReporting Instance Status = 'pending'")
                .endParam()
                .to("direct:RetrieveCustomerCreditRatingBehaviorQualifierReferenceIds");
    }
    
}
